### ISSUE TITLE
opensource code pls

### ISSUE THREAD

**Issue by xrivendell7** [Stab1el/BAGUA#1]
Hello, I'm very intersted in your project and paper in NDSS 2023.
Do you have open source plans and when?

**Comment by Stab1el** [comment]
Thanks for your attention! We are now optimizing our code of the project, and we will release our code in about two months.

**Comment by danmaam** [comment]
any update on this? we are really interested in trying your approach

**Comment by Stab1el** [comment]
Thank you for your interest in our paper, due to some technical reasons, the open source work has been delayed slightly. We are optimizing our code and will open source it in the next 1 to 2 weeks.
