### ISSUE TITLE
Release code for primitive generation

### ISSUE THREAD

**Issue by danmaam** [Stab1el/BAGUA#4]
Hello
We're looking at BAGUA's code, but we could not find any code to dump the primitives from a binary executable.
Can you make it open-source?
Thank you

**Comment by Stab1el** [comment]
Hi, thanks for your concern. As has been stated in the paper, we want to make BAGUA applicable to more target applications, and more work is still conducted now.  

For sake of researchers to verify the performance of automatic heap layout manipulation,  we will provide a comprehensive benchmark, which could generate different kinds of primitives.
